# Licensed to ObjectStyle LLC under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ObjectStyle LLC licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: bootique-tool

on: [push, pull_request]

jobs:
  deploy-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v2
        with:
          path: $HOME/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - run: mvn package

      - name: script
        run: chmod +x ./deploy/linux.sh;
            ./deploy/linux.sh;

      - name: before_deploy
        run: chmod +x ./deploy/update-version.sh;
            ./deploy/update-version.sh;

      - name: Upload deb package to Bintray
        uses: bpicode/github-action-upload-bintray@master
#        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          file: bootique-tool/target/bq-0.100.deb
          api_user: kravchenko
          api_key: ${{ secrets.BINTRAY_API_KEY }}
#          gpg_passphrase: ${{ secrets.BINTRAY_GPG_PASSPHRASE }} # Optional, for this to work Bintray requires a GPG public/private keypair configured for the repository owner (individual or organization).
          repository_user: kravchenkoas
          repository: bq-tool-my-repo-deb
          package: bq-deb
          version: 0.100-SNAPSHOT
          upload_path: pool/main/m # Typical for debian repository layout
          publish: 0
          calculate_metadata: true # Schedule metadata calculation after upload
          deb_distribution: wheezy
          deb_component: main
          deb_architecture: amd64

#      - name: Upload rpm package to Bintray
#        uses: wanduow/action-bintray-upload-rpm-packages@v1
##        if: ${{ github.ref == 'refs/heads/master' }}
#        with:
#          path: ./target/bq-0.100.rpm
#          repo: kravchenkoas/bq-tool-my-repo-rpm
#          username: kravchenko
#          api_key: ${{ secrets.BINTRAY_API_KEY }}

      - name: Upload rpm package to Bintray
        uses: reznikmm/upload-bintray-action@v2
        with:
          subject: kravchenkoas
          repository: bq-tool-my-repo-rpm
          package: bq-rpm
          version: 0.100-SNAPSHOT
          sourcePath: './target/bq-0.100.rpm'
          override: 0
          username: kravchenko
          apiKey: ${{ secrets.BINTRAY_API_KEY }}

  deploy-macos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v2
        with:
          path: $HOME/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - run: mvn package

      - name: script
        run: chmod +x ./deploy/mac.sh;
          ./deploy/mac.sh;

      - name: before_deploy
        run: chmod +x ./deploy/update-mac-version.sh;
          ./deploy/update-mac-version.sh;

      - name: Upload zip package to Bintray
        uses: masofcon/upload-to-bintray-github-action@master
#        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          source_path: bootique-tool/target/bq-0.100.zip
          api_user: kravchenko
          api_key: ${{ secrets.BINTRAY_API_KEY }}
#          gpg_passphrase: ${{ secrets.BINTRAY_GPG_PASSPHRASE }} # Optional, for this to work Bintray requires a GPG public/private keypair configured for the repository owner (individual or organization).
          repository: bq-tool-my-repo-mac
          package: bq
          version: 0.100-SNAPSHOT
          upload_path: pool/main/m
          publish: 0

      - name: after_deploy
        run: chmod +x ./deploy/update-homebrew.sh;
            ./deploy/update-homebrew.sh;